package:
  name: llvmpy
  version: 0.12.7rc1

# build:
#  number: 2   # 7d7dddeb9ffe36fcc151cb58e3eabd4fdf35b6d5

source:
  git_url: https://github.com/llvmpy/llvmpy.git
  git_tag: 0.12.7rc1

requirements:
  build:
    - llvm
    - python
  run:
    - llvm           [unix]
    - python

test:
  requires:
    - unittest2      [py26]
  imports:
    - llvm
    - llvmpy
    - llvmpy._api
    - llvmpy._capsule
    - llpython
    - llvm_array
    - llvm_cbuilder


