package:
  name: llvmpy
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  
source:
  git_url: https://github.com/llvmpy/llvmpy.git
  # git_tag: 0.12.7rc1

requirements:
  build:
    - llvm
    - python
  run:
    - llvm           [unix]
    - python

test:
  requires:
    - unittest2      [py26]
  imports:
    - llvm
    - llvmpy
    - llvmpy._api
    - llvmpy._capsule
    - llpython
    - llvm_array
    - llvm_cbuilder


