package:
   name: numba
   version: latest

source:
  git_url: git@github.com:numba/numba.git
  # git_tag: 0.10.0

requirements:
  build:
    - numpy
    - python
  run:
    - python
    - argparse        [py26]
    - numpy
    - llvmpy
    - cudatoolkit

test:
  requires:
    - unittest2      [py26]
  commands:
    - pycc -h
    - numba -h
