package:
  name: numba
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: https://github.com/numba/numba.git
  # git_tag: 0.13.4rc3

requirements:
  build:
    - numpy
    - python
  run:
    - python
    - argparse        [py26]
    - numpy
    - llvmpy
    - cudatoolkit

test:
  requires:
    - unittest2      [py26]
  commands:
    - pycc -h
    - numba -h
