package:
  name: numba
  version: 0.13.4rc3

#build:
#  number: 1   # 4a0d41e32da40b2ee16ca94f36b83f74ea351871

source:
  git_url: https://github.com/numba/numba.git
  git_tag: 0.13.4rc3

requirements:
  build:
    - numpy
    - python
  run:
    - python
    - argparse        [py26]
    - numpy
    - llvmpy
    - cudatoolkit

test:
  requires:
    - unittest2      [py26]
  commands:
    - pycc -h
    - numba -h
